version: '3.4'

services:
  db:
    restart: always
    container_name: ${DB_NAME}
    image: postgres:13.13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./etc/db:/var/lib/postgresql