name: publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  create-docker-image:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_CD }}
        
      - name: Build the Docker image
        run: |
          docker build . --tag ghcr.io/mhp24/papa-johns-api:latest
          docker push ghcr.io/mhp24/papa-johns-api:latest  
  